version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -qq https://github.com/pyannote/pyannote-audio/archive/refs/heads/develop.zip
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Pre-build phase...
      # Run tests here, if any
  build:
    commands:
      - echo Build phase...
      - echo Creating application source bundle...
      - zip ./app_source.zip -r * .[^.]* -x buildspec.yml -x '*.git*'
artifacts:
  files:
    - app_source.zip