version: 0.2

phases:
  pre_build:
    commands:
      - echo Preparing to validate Dockerfile...
      - docker --version
  build:
    commands:
      - echo Validating Dockerfile...
      - docker build -t validate-dockerfile .
  post_build:
    commands:
      - echo Dockerfile has been validated successfully.

artifacts:
  files:
    - Dockerfile
    - ./**/*
  discard-paths: yes
