version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing source dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: yes
